services:
  app:
    build: .
    environment:
      DB_URL: jdbc:postgresql://db:5432/bankdb
      DB_USER: postgres
      DB_PASSWORD: 123
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: bank_springboot_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app-network



volumes:
  data:


networks:
  app-network:
    driver: bridge

